version: '3'

services:
  # Prometheus Service
  prometheus:
    image: prom/prometheus:v2.39.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # Grafana Service
  grafana:
    image: grafana/grafana:8.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # Default password for Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

  # Node Exporter Service (For node metrics)
  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    ports:
      - "9100:9100"  # Node exporter metrics exposed
    networks:
      - monitoring

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: bridge

