global:
  scrape_interval: 15s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+):(.+)
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['a4236b55a70a64bf1bd14defe55f0121-1531097612.us-east-1.elb.amazonaws.com:8080']
  
  - job_name: 'amazon-prime-cluster'
    honor_timestamps: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['a4236b55a70a64bf1bd14defe55f0121-1531097612.us-east-1.elb.amazonaws.com:8080']
    metric_relabel_configs:
      - target_label: 'cluster'
        replacement: 'amazon-prime-cluster'

